# Optimized for QueryPie 11.0.x - Database Profile
# Compatible with both Docker and Podman

name: querypie
services:
  mysql:
    hostname: mysql
    networks:
      - database-network
    image: docker.io/querypie/mysql:8.0.42
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_CATALOG:?ex. querypie}

  redis:
    hostname: redis
    networks:
      - database-network
    image: docker.io/querypie/redis:7.4.5
    ports:
      - "6379:6379"
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"]

volumes:
  mysql-data:
    driver: local # By default, the size of this volume is unlimited.

networks:
  database-network:
    name: querypie-database
    driver: bridge

x-podman:
  # Use - for container name separator to be compatible with Docker Compose v2.
  name_separator_compat: true
